import type { SignatureDefinition } from "./types";

/**
 * Regras iniciais, mantidas isoladas do motor. Indicadores curtos são
 * deliberadamente marcados como fracos e nunca confirmam um achado sozinhos.
 */
export const defaultSignatures: SignatureDefinition[] = [
  {
    id: "rx7-att",
    name: "ATT",
    category: "Privacidade e perfis",
    indicator: "ATT",
    type: "string",
    severity: "informativo",
    baseConfidence: "informativo",
    expectedFiles: ["McSettings", "McSettingsEvents", "SystemProfile"],
    expectedKeys: ["ATT", "TrackingAuthorizationStatus"],
    contextExpected: ["tracking", "authorization", "privacy"],
    description: "Referência de contexto relacionada a App Tracking Transparency. Por si só, não indica alteração ou risco.",
    isWeak: false,
    weight: 2,
  },
  {
    id: "rx7-zeex-06",
    name: "Zeex Free/VIP — 06",
    category: "Zeex Free/VIP",
    indicator: "06",
    type: "string",
    severity: "baixa",
    baseConfidence: "baixa",
    expectedFiles: ["McSettings", "McSettingsEvents", "McProfile"],
    expectedKeys: [],
    contextExpected: ["zeex", "proxy", "profile"],
    description: "Sequência curta e genérica. É sinal fraco e exige contexto correlacionado para aumentar a confiança.",
    isWeak: true,
    weight: 1,
  },
  {
    id: "rx7-zeex-78f",
    name: "Zeex Free/VIP — 78f",
    category: "Zeex Free/VIP",
    indicator: "78f",
    type: "string",
    severity: "baixa",
    baseConfidence: "baixa",
    expectedFiles: ["McSettings", "McSettingsEvents", "McProfile"],
    expectedKeys: [],
    contextExpected: ["zeex", "proxy", "profile"],
    description: "Sequência curta e genérica. É sinal fraco e exige contexto correlacionado para aumentar a confiança.",
    isWeak: true,
    weight: 1,
  },
  {
    id: "rx7-zeex-140",
    name: "Zeex Free/VIP — 140",
    category: "Zeex Free/VIP",
    indicator: "140",
    type: "string",
    severity: "baixa",
    baseConfidence: "baixa",
    expectedFiles: ["McSettings", "McSettingsEvents", "McProfile"],
    expectedKeys: [],
    contextExpected: ["zeex", "proxy", "profile"],
    description: "Sequência curta e genérica. É sinal fraco e exige contexto correlacionado para aumentar a confiança.",
    isWeak: true,
    weight: 1,
  },
  {
    id: "rx7-zeex-d14",
    name: "Zeex Free/VIP — d14",
    category: "Zeex Free/VIP",
    indicator: "d14",
    type: "string",
    severity: "baixa",
    baseConfidence: "baixa",
    expectedFiles: ["McSettings", "McSettingsEvents", "McProfile"],
    expectedKeys: [],
    contextExpected: ["zeex", "proxy", "profile"],
    description: "Sequência curta e genérica. É sinal fraco e exige contexto correlacionado para aumentar a confiança.",
    isWeak: true,
    weight: 1,
  },
  {
    id: "rx7-zeex-d4",
    name: "Zeex Free/VIP — d4",
    category: "Zeex Free/VIP",
    indicator: "d4",
    type: "string",
    severity: "baixa",
    baseConfidence: "baixa",
    expectedFiles: ["McSettings", "McSettingsEvents", "McProfile"],
    expectedKeys: [],
    contextExpected: ["zeex", "proxy", "profile"],
    description: "Sequência curta e genérica. É sinal fraco e exige contexto correlacionado para aumentar a confiança.",
    isWeak: true,
    weight: 1,
  },
  {
    id: "rx7-dash-proxy",
    name: "DASH proxy",
    category: "DASH",
    indicator: "dash-proxy",
    type: "plist-value",
    severity: "alta",
    baseConfidence: "alta",
    expectedFiles: ["McSettings", "McSettingsEvents", "Network", "Preferences"],
    expectedKeys: ["Proxy", "HTTPProxy", "HTTPSProxy", "Server"],
    contextExpected: ["proxy", "network", "configuration"],
    description: "Indicador específico cuja relevância é avaliada apenas com caminho, chave ou contexto de rede compatível.",
    isWeak: false,
    weight: 7,
  },
  {
    id: "rx7-external-cert-appdb",
    name: "Certificado externo AppDB",
    category: "Certificados externos",
    indicator: "to-appdb-certs1",
    type: "certificate",
    severity: "alta",
    baseConfidence: "alta",
    expectedFiles: ["Certificate", "Trust", "SystemProfile", "McProfile"],
    expectedKeys: ["Certificate", "PayloadContent", "Subject"],
    contextExpected: ["certificate", "profile", "trust"],
    description: "Nome específico associado a certificado externo. O relatório preserva o local e o contexto, sem diagnóstico definitivo.",
    isWeak: false,
    weight: 8,
  },
];
